title: "Bug Report: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to file a bug report!

  - type: textarea
    id: bug
    attributes:
      label: Problem encountered
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: observed
    attributes:
      label: Observed behaviour
      description: "A clear and concise description of how the system is behaving."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: "Detail the steps to reproduce the behaviour"
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Observe the error
        ...
      render: bash
      render: bash
    validations:
      required: true

  - type: input
    id: has-id
    attributes:
      label: pub-key
      description: Please add your vega pubkey to help investigations.
    validations:
      required: false

  - type: textarea
    id: system-info
    attributes:
      label: System information
      description: "Add any other context about the problem here including; system version numbers, components affected."
    validations:
      required: true

  - type: textarea
    id: visual-info
    attributes:
      label: Screenshots and videos
      description: "Add any other context about the problem here including; screenshots and videos."
    validations:
      required: false
